#!/bin/bash

sudo apt update -y
sudo apt install nginx -y
sudo systemctl start nginx
sudo systemctl enable nginx
sudo systemctl status nginx

_______________________________________________________

chmod +x setup.sh
./setup.sh

This is how admins stop repeating themselves.
